<?php 
$tableParams = array(
	'tableId' 			=> 'samples-general-tree',
    'tableWidth'        => '4',
);
?>

<?php echo $this->zrayTable($tableParams); //zrayTableHtml ?>

<script type="text/javascript">

(function() {
	var storage = zray.getStorage('samplesGeneralTree');

	// create main table
	var maintable = zray.createGeneralTreeTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	maintable.setColumns([{
		label: 'col1',
		propertyName: 'col1',
		width: '25%',
		attributes: {'class': 'zdb-tree-table-cell-path zdb-ellipsis zdb-monospace'}
	},
	{
		label: 'col2',
		propertyName: 'col2',
		width: '75%',
		attributes: {'class': 'zdb-monospace zdb-ellipsis'},
		getHtml: function(val, rec) {
			var cushion = $zendDevBar('<div>');
			cushion.attr('title', val);
			return cushion.text(val);
		}
	},
	{
		label: 'params',
		propertyName: 'params',
		width: '75%',
		attributes: {'class': 'zdb-monospace zdb-ellipsis'},
		getHtml: function(val, rec) {
			var cushion = $zendDevBar('<div>');
			cushion.attr('title', val);
			return cushion.text(val);
		}
	}]);
	// create main table - end
	
	zray.registerDataHandler('Samples', 'multiplyGeneralTree', function(extensionData, requestData) {
		storage.setData(extensionData);
	});
})();
</script>